### ISSUE TITLE
global flags

### ISSUE THREAD

**Issue by sstarcher** [nicolas-nannoni/aws-sts-helper#4]
global flags don't look to be persisting past the top level.

```
aws-sts get-token --debug --role-arn arn:aws:iam::xxx:role/xxx  and-show-export
Incorrect Usage.
```

**Comment by nicolas-nannoni** [comment]
I know, that's a bit annoying... It's a bug in urfave/cli#585. It doesn't seem fixed yet, but someone provided a workaround. I may add that to make it a bit less cumbersome but that clutters the code quite a bit.
