### ISSUE TITLE
non-standard import

### ISSUE THREAD

**Issue by danzelziggy** [nicolas-nannoni/aws-sts-helper#5]
Manually installing the packages didn't help at all and using Go1.6

can't load package: /usr/lib/go-1.6/src/aws-sts-helper/helper.go:8:2: local import "./config" in non-local package
/usr/lib/go-1.6/src/aws-sts-helper/sts/sts.go:13:2: non-standard import "github.com/aws/aws-sdk-go/aws" in standard package "_/usr/lib/go-1.6/src/aws-sts-helper/sts"

**Comment by danzelziggy** [comment]
Reinstalling Go reduced to these error:

can't load package: /usr/share/go/src/aws-sts-helper/helper.go:8:2: local import "./config" in non-local package

**Comment by danzelziggy** [comment]
Fixing path did the trick but dont know what to do here:

# _/usr/share/go/aws-sts-helper/sts
sts/sts.go:12: imported and not used: "github.com/Sirupsen/logrus"
sts/sts.go:50: undefined: log in log.Info
sts/sts.go:67: undefined: log in log.Info
sts/sts.go:75: undefined: log in log.Info
sts/sts.go:89: undefined: log in log.Fatalf
sts/sts.go:100: undefined: log in log.Debugf
sts/sts.go:107: undefined: log in log.Fatalf
sts/sts.go:110: undefined: log in log.Infof
sts/sts.go:121: undefined: log in log.Debugf
sts/sts.go:127: undefined: log
sts/sts.go:127: too many errors

**Comment by nicolas-nannoni** [comment]
I don't know how you were trying to use it but the project needed to be in your GOPATH to be compiled because of the local/relative imports. I changed those to regular imports. Maybe that helps with your issues?

**Comment by danzelziggy** [comment]
Here's my Go env looks like:

# go env
GOARCH="amd64"
GOBIN="/usr/share/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/share/go"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

same error when running "go get github.com/nicolas-nannoni/aws-sts-helper"

running "make":
rm -Rf bin
# github.com/nicolas-nannoni/aws-sts-helper/sts
sts/sts.go:18: imported and not used: "github.com/Sirupsen/logrus"
sts/sts.go:52: undefined: log in log.Info
sts/sts.go:69: undefined: log in log.Info
sts/sts.go:77: undefined: log in log.Info
sts/sts.go:91: undefined: log in log.Fatalf
sts/sts.go:102: undefined: log in log.Debugf
sts/sts.go:109: undefined: log in log.Fatalf
sts/sts.go:112: undefined: log in log.Infof
sts/sts.go:123: undefined: log in log.Debugf
sts/sts.go:129: undefined: log
sts/sts.go:129: too many errors
Makefile:20: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by danzelziggy** [comment]
I did fix the issue by fixing the uppercase/lowercase issue as mentioned in https://github.com/Sirupsen/logrus and putting log in front both in helper.go and sts\sts.go files.

![helper-go](https://user-images.githubusercontent.com/548233/32591663-3137888c-c55b-11e7-9b42-2651192c23f0.png)
![sts-go](https://user-images.githubusercontent.com/548233/32591664-316eb910-c55b-11e7-91f8-8eb34c507e81.png)
 
Sadly, you removed windows build which I needed the most for cyberduck purposes. I would highly appreciate it if you can put it back. Thank you so much and this projects is really helpful and simplifying in getting AWS STS.

**Comment by danzelziggy** [comment]
Adding this line below in the Makefile did create a windows build.

![makefile](https://user-images.githubusercontent.com/548233/32593674-befaa192-c563-11e7-9b64-975b381034e3.png)

testing in win10pro:

![aws](https://user-images.githubusercontent.com/548233/32593708-efafc06a-c563-11e7-9d92-27029c43b5a6.png)

Let me test if this will actually work on aws ec2 win2012r2

**Comment by nicolas-nannoni** [comment]
Oh, you are using it on Windows? I actually never tested it on Windows (I wasn't even publishing the binaries for it) because I assumed that given that the shell is different, it probably wouldn't be useful. But now that you mention the HTTP use, I see how it makes sense!

I also fixed the logrus thing. I knew about it but I did the changes real quick yesterday and just forgot it. Now it should be fixed in this [PR](https://github.com/nicolas-nannoni/aws-sts-helper/pull/8). I managed to `go get -u` on the project without troubles. I compiled the binaries for Windows and attached them there: @danzelziggy if you could have a look and see if it works that would be great. I would then merge and publish the new version with everything finally in place, including Windows binaries. Thanks for your help!

**Comment by danzelziggy** [comment]
Thanks so much @nicolas-nannoni ! So much considerate of you. I can't promise any exact day but will have to test it next week. Glad I could help. :)

**Comment by nicolas-nannoni** [comment]
Since the import path is fixed and the binaries for Windows are back, I'll close that issue and let you test. I released the changes and updated the PR given your comments. If you find anything wrong, feel free to reopen that one or create a new issue. Thanks!

**Comment by danzelziggy** [comment]
Confirmed working in windows!

![windows](https://user-images.githubusercontent.com/548233/33163742-d3986ee2-d06a-11e7-87da-f1fdfb323dc8.PNG)

**Comment by danzelziggy** [comment]
Serving via http only works via localhost in windows. Using public ip doesn't work even windows firewall off.
